# Generated by Django 3.1.5 on 2021-02-05 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20210131_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
