# Generated by Django 3.1.5 on 2021-02-13 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0007_comment_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('LA', 'Language'), ('AB', 'Abuse'), ('OF', 'Offensive'), ('OT', 'Other')], default='OT', max_length=2)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_flags', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
